### ISSUE TITLE
Installing plugins from the Command line

### ISSUE THREAD

**Issue by jan-dh** [nystudio107/craft3-multi-environment#3]
When trying to install a plugin from the command line, I get the error `Unsupported DB driver value: `. Value seems empty. This is a on a fresh install. I can install Craft, I can login to the admin panel. Removing the driver option from the db.php then gives `Craft CMS can’t connect to the database with the credentials in config/db.php.`.

**Comment by khalwat** [comment]
This is likely because you didn't apply the changes to the `craft` executable as outlined in the docs
